parameters:
  documents_directory: '%kernel.project_dir%/public/uploads/documents'

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../src/*'
    exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

  App\Controller\:
    resource: '../src/Controller'
    tags: ['controller.service_arguments']

  App\Service\FileUploader:
    arguments:
      $target: '%documents_directory%'
