security:
  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: mail
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      anonymous: ~
      guard:
        authenticators:
          - App\Security\LoginAuthenticator
      logout:
        path: app_logout
  encoders:
    App\Entity\User:
      algorithm: auto
