// Generated by Selenium IDE
import com.gargoylesoftware.htmlunit.BrowserVersion;
import com.gargoylesoftware.htmlunit.WebClient;
import org.junit.Assert;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.htmlunit.HtmlUnitDriver;
import org.openqa.selenium.interactions.Actions;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;

public class ADM2PTest {
  private WebDriver driver;
  @Before
  public void setUp() {
    driver = new HtmlUnitDriver(true) {
      @Override
      protected WebClient newWebClient(BrowserVersion version) {
        WebClient webClient = super.newWebClient(version);
        webClient.getOptions().setThrowExceptionOnScriptError(false);
        return webClient;
      }
    };
    driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
    java.util.logging.Logger.getLogger("com.gargoylesoftware").setLevel(Level.OFF);
    System.setProperty("org.apache.commons.logging.Log", "org.apache.commons.logging.impl.NoOpLog");
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void aDM2P() {
    driver.get(Adresse.getAdresse());
    driver.manage().window().setSize(new Dimension(1346, 918));
    driver.findElement(By.id("mail")).click();
    driver.findElement(By.id("mail")).sendKeys("admin@univ-fcomte.fr");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("1234");
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.linkText("Utilisateurs")).click();
    driver.findElement(By.linkText("Modifier")).click();
    {
      WebElement dropdown = driver.findElement(By.id("user_roles"));
      dropdown.findElement(By.xpath("//option[. = 'Responsable']")).click();
    }
    driver.findElement(By.id("user_submit")).click();
    String URL = driver.getCurrentUrl();
    String attendu=Adresse.getAdresse()+"users";
    Assert.assertEquals(URL, attendu);
    assertThat(driver.findElement(By.cssSelector(".alert")).getText(), is("L'utilisateur Basic user a bien \u00e9t\u00e9 modifi\u00e9."));
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(1) > .align-middle:nth-child(4)")).getText(), is("ROLE_USER, ROLE_RESP"));
    driver.findElement(By.linkText("D\u00e9connexion")).click();
  }
}
