// Generated by Selenium IDE
import com.gargoylesoftware.htmlunit.BrowserVersion;
import com.gargoylesoftware.htmlunit.WebClient;
import org.hamcrest.core.Is;
import org.junit.Assert;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.hamcrest.MatcherAssert.assertThat;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.htmlunit.HtmlUnitDriver;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;

public class INT1Test {
  private WebDriver driver;
  @Before
  public void setUp() {
    driver = new HtmlUnitDriver(true) {
      @Override
      protected WebClient newWebClient(BrowserVersion version) {
        WebClient webClient = super.newWebClient(version);
        webClient.getOptions().setThrowExceptionOnScriptError(false);
        return webClient;
      }
    };
    driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
    java.util.logging.Logger.getLogger("com.gargoylesoftware").setLevel(Level.OFF);
    System.setProperty("org.apache.commons.logging.Log", "org.apache.commons.logging.impl.NoOpLog");
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void untitled() {
    driver.get(Adresse.getAdresse());
    driver.manage().window().setSize(new Dimension(897, 837));
    driver.findElement(By.id("mail")).click();
    driver.findElement(By.id("mail")).sendKeys("resp@univ-fcomte.fr");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("1234");
    driver.findElement(By.cssSelector(".btn")).click();

    driver.findElement(By.linkText("Ing\u00e9nierie dirig\u00e9e pas les mod\u00e8les")).click();
    driver.findElement(By.linkText("Cr\u00e9er un sujet")).click();
    driver.findElement(By.id("subject_name")).click();
    driver.findElement(By.id("subject_name")).sendKeys("sujet1");
    driver.findElement(By.id("subject_description")).click();
    driver.findElement(By.id("subject_description")).sendKeys("description");
    driver.findElement(By.id("subject_type")).click();
    {
      WebElement dropdown = driver.findElement(By.id("subject_type"));
      dropdown.findElement(By.xpath("//option[. = 'TD']")).click();
    }
    driver.findElement(By.cssSelector("option:nth-child(2)")).click();
    driver.findElement(By.id("subject_document")).click();
    driver.findElement(By.id("subject_document")).sendKeys("C:\\fakepath\\REDIGER UNE INTRODUCTION.pdf");
    driver.findElement(By.id("subject_submit")).click();
   // assertThat(driver.findElement(By.cssSelector("tr:nth-child(1) > .align-middle:nth-child(2)")).getText(), is("sujet1"));
  //  assertThat(driver.findElement(By.cssSelector("tr:nth-child(1) > .align-middle:nth-child(4)")).getText(), is("ROLE_USER, ROLE_RESP"));
    //assertThat(driver.findElement(By.cssSelector("tr:nth-child(1) > .align-middle:nth-child(3)")).getText(), is("TD"));

    driver.findElement(By.linkText("D\u00e9connexion")).click();

  }

}
